### ISSUE TITLE
It does not work with Chimera 1.12

### ISSUE THREAD

**Issue by lvelasco022** [insilichem/gpathfinder#5]
I tried to run gpathfinder using the Chimera version 1.12, that it was the one I had previously installed, and the following error appeared:

>Traceback (most recent call last):
  File "/Users/Lorea/anaconda/envs/gpathfinder/bin/pychimera", line 11, in <module>
    import pychimera._main_
  File "/Users/Lorea/anaconda/envs/gpathfinder/lib/python2.7/site-packages/pychimera/_init_.py", line 4, in <module>
    from .core import main, patch_environ, enable_chimera, load_chimera, _version_
  File "/Users/Lorea/anaconda/envs/gpathfinder/lib/python2.7/site-packages/pychimera/core.py", line 16, in <module>
    import argparse
  File "/Users/Lorea/anaconda/envs/gpathfinder/lib/python2.7/argparse.py", line 86, in <module>
    import copy as _copy
  File "/Users/Lorea/anaconda/envs/gpathfinder/lib/python2.7/copy.py", line 52, in <module>
    import weakref
  File "/Users/Lorea/anaconda/envs/gpathfinder/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref

I recommend using the latest version of Chimera, since using a more recent version of Chimera (1.13 or 1.14) is enough to overcome the error.
